name=Felix8A
version=1.0.1
author=Felix Ochoa
maintainer=Felix Ochoa
sentence=Lightweight 32-bit hexadecimal color utility library for Arduino.
paragraph=Provides fast and reusable tools for working with 32-bit hexadecimal colors.
category=Display
url=https://github.com/felixthecat8a/Felix8A
architectures=*
