name=Felix8A
version=1.1.1
author=Felix Ochoa
maintainer=Felix Ochoa
sentence=Arduino toolkit for handling components in projects.
paragraph=Toolkit for digital, PWM & RGB LED control, push button signal handling,32-bit hexadecimal color utilities, non-blocking time task management.
category=Device Control
url=https://github.com/felixthecat8a/Felix8A
architectures=*
